{% set python_min = '3.10' %}
{% set name = "myst-parser" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 851c9dfb44e36e56d15d05e72f02b80da21a9e0d07cba96baf5e2d476bb91531

build:
  number: 1
  entry_points:
    - myst-benchmark = myst_parser.cli.benchmark:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.4,<4
  run:
    - docutils >=0.19,<0.22
    - markdown-it-py >=3.0.0,<4.0.0
    - mdit-py-plugins >=0.4.1,<1
    - jinja2
    - python >={{ python_min }}
    - pyyaml
    - sphinx >=7,<9

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - myst_parser
    - myst_parser.cli

about:
  home: https://github.com/ExecutableBookProject/MyST-Parser
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: An extended commonmark compliant parser, with bridges to docutils & sphinx.
  doc_url: https://myst-parser.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
    - choldgraf
