{% set python_min = "3.10" %}
{% set name = "myst-parser" %}
{% set version = "4.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: "{{ name|lower }}-{{ version }}.tar.gz"
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5cfea715e4f3574138aecbf7d54132296bfd72bb614d31168f48c477a830a7c4

build:
  number: 0
  entry_points:
    - myst-anchors = myst_parser.cli:print_anchors
    - myst-benchmark = myst_parser.cli.benchmark:main
    - myst-inv = myst_parser.inventory:inventory_cli
    - myst-docutils-html = myst_parser.parsers.docutils_:cli_html
    - myst-docutils-html5 = myst_parser.parsers.docutils_:cli_html5
    #- myst-docutils-demo = myst_parser.parsers.docutils_:cli_html5_demo
    - myst-docutils-latex = myst_parser.parsers.docutils_:cli_latex
    - myst-docutils-xml = myst_parser.parsers.docutils_:cli_xml
    - myst-docutils-pseudoxml = myst_parser.parsers.docutils_:cli_pseudoxml
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - flit-core >=3.4,<4
  run:
    - docutils >=0.19,<0.22
    - markdown-it-py >=3.0.0,<4.0.0
    - mdit-py-plugins >=0.4.1,<1
    - jinja2
    - python >={{ python_min }}
    - pyyaml
    - sphinx >=7,<9

test:
  requires:
    - pip
  commands:
    - pip check
    - myst-anchors --help
    - myst-inv --help
    - myst-docutils-html --help
    - myst-docutils-html5 --help
    #- myst-docutils-demo --help
    - myst-docutils-latex --help
    - myst-docutils-xml --help
    - myst-docutils-pseudoxml --help
  imports:
    - myst_parser
    - myst_parser.cli

about:
  home: https://github.com/executablebooks/MyST-Parser
  license: MIT
  license_file: LICENSE
  summary: An extended CommonMark compliant parser, with bridges to docutils & sphinx.
  dev_url: https://github.com/executablebooks/MyST-Parser
  doc_url: https://myst-parser.readthedocs.io

extra:
  recipe-maintainers:
    - dopplershift
    - choldgraf
    - chenghlee
